parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     8080
    database_name:     bainvill2u_LP_projet
    database_user:     bainvill2u_appli
    database_password: 31114627	

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
