<?php

namespace Projet\ProjetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * uniteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uniteRepository extends EntityRepository
{
}
