projet_projet_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ProjetProjetBundle:Default:index }

projet_projet_accueil:
    path:     /accueil
    defaults: { _controller: ProjetProjetBundle:Projet:accueil }

projet_projet_attestation_scolarite:
    path:     /attestation_scolarite
    defaults: { _controller: ProjetProjetBundle:Projet:scolarite }