parameters:
#    projet_projet.example.class: Projet\ProjetBundle\Example

services:
#    projet_projet.example:
#        class: %projet_projet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
