<?php

namespace Projet\ProjetBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ProjetController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Projet\ProjetBundle\Controller\ProjetController();
        return $instance;
    }
}
